services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: